name: Python CI pipeline

on:
  push:
    branches: [ "main", "master","py_scraper" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./python_scraper

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v6

    - name: Setup Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: "pip"

    - name: Installazione dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Controllo Formattazione
      run: |
        black --check src tests

    - name: Controllo Tipizzazione
      run: |
        pyright src tests

    - name: Esecuzione dei test con Coverage
      run: |
        pytest --cov=src --cov-report=term-missing --cov-fail-under=80